CREATE TABLE Schools (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Address TEXT NOT NULL
);

CREATE TABLE Classes (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    SchoolId INTEGER NOT NULL,
    Name TEXT NOT NULL,
    FOREIGN KEY (SchoolId) REFERENCES Schools(Id)
);

CREATE TABLE Students (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    ClassId INTEGER NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    BirthDate DATETIME NOT NULL,
    FOREIGN KEY (ClassId) REFERENCES Classes(Id)
);
